apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  labels:
    app: test
    tier: messaging
spec:
  type: ClusterIP
  selector:
    app: test
    tier: messaging
  ports:
    - port: 5672
      targetPort: 5672

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: test
      tier: messaging
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: test
        tier: messaging
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7.7-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
