apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  labels:
    app: test
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: test
    tier: frontend
  ports:
    - port: 80
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: test
      tier: frontend
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: test
        tier: frontend
    spec:
      containers:
        - name: web
          image: weibeld/ktest-web:latest
          env:
            - name: AMQP_URI
              value: amqp://messaging-service
            - name: QUEUE
              value: requests
          ports:
            - containerPort: 3000
