apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-service
  labels:
    app: test
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: test
    tier: backend
  ports:
    - port: 80
      targetPort: 15672

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: test
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: test
    tier: backend 
  ports:
    - port: 5672
      targetPort: 5672

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-and-rabbitmq
spec:
  selector:
    matchLabels:
      app: test
      tier: backend
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: test
        tier: backend
    spec:
      containers:
        - name: core
          image: weibeld/ktest-core
          env:
            - name: AMQP_URI
              value: amqp://localhost
            - name: QUEUE
              value: requests
        - name: rabbitmq
          image: rabbitmq:3.7.7-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
